# Generated by Django 3.2.7 on 2021-10-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productimage_thumbnail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
    ]
