# Generated by Django 3.2.7 on 2021-10-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productimage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
