# Generated by Django 3.2.7 on 2021-10-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20211012_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
