# Generated by Django 3.2.7 on 2021-10-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productimage_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
