# Generated by Django 3.2.7 on 2021-10-13 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20211012_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='category',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='product_category_id',
            field=models.ForeignKey(db_column='product_category_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='product.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory_id',
            field=models.ForeignKey(db_column='subcategory_id', default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='product.productsubcategory'),
        ),
    ]
