# Generated by Django 3.2.7 on 2021-10-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20211013_1036'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
        migrations.AlterModelTable(
            name='productsubcategory',
            table='product_subcategory',
        ),
    ]
