# Generated by Django 3.2.7 on 2021-10-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20211013_1427'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
    ]
