# Generated by Django 3.2.7 on 2021-10-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_social_id'),
        ('product', '0013_alter_productcategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(db_column='parent_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.qna')),
                ('product', models.ForeignKey(db_column='product_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('user', models.ForeignKey(db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
