# Generated by Django 3.2.7 on 2021-10-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='content',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AlterModelTable(
            name='qna',
            table='qna',
        ),
    ]
