# Generated by Django 3.2.7 on 2021-10-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20211013_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='content',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='parent',
        ),
        migrations.AddField(
            model_name='qna',
            name='question',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
