# Generated by Django 3.2.7 on 2021-10-10 04:28

from django.db import migrations, models
import django.db.models.deletion
import seller.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_user_social_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='상품명')),
                ('address', models.TextField(verbose_name='주소')),
                ('address_detail', models.TextField(verbose_name='상세주소')),
                ('phone_number', models.TextField(verbose_name='전화번호')),
                ('mobile_number', models.TextField(verbose_name='휴대전화 번호')),
                ('image', models.ImageField(blank=True, null=True, upload_to=seller.models.PathAndRename('seller/'))),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품입니다',
                'db_table': 'seller',
            },
        ),
    ]
