# Generated by Django 3.2.7 on 2021-09-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_login',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='소셜로그인'),
        ),
    ]
