# Generated by Django 3.2.7 on 2021-10-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='비밀번호'),
        ),
    ]
