# Generated by Django 3.2.7 on 2021-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.FileField(default=None, max_length=128, null=True, upload_to=''),
        ),
    ]
