# Generated by Django 3.2.7 on 2021-10-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='소셜 아이디'),
        ),
    ]
