# Generated by Django 3.2.7 on 2021-10-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table='bookmark',
        ),
    ]
